import { Inject, Injectable } from "@nestjs/common";
import { AppException } from "@/common/exceptions/app-exception";
import { APP_ERRORS } from "@/common/exceptions/app-errors.catalog";
import { StoreAuthorizationService } from "@/modules/stores/application/use-cases/store-authorization.use-case";
import { StorePermission } from "@/modules/stores/domain/enums/store-permission.enum";
import {
  PRODUCT_REPOSITORY,
  type ProductRepositoryPort,
  type ProductView,
} from "@/modules/catalog/application/ports/product-repository.port";
import { UpdateProductCommand } from "@/modules/catalog/application/dto/product.commands";
import {
  assertValidKind,
  assertValidPackagingUnit,
  assertValidUnit,
  normalizePackSize,
  normalizeSalePrice,
} from "@/modules/catalog/domain/entities/product.entity";

@Injectable()
export class UpdateProductUseCase {
  constructor(
    @Inject(PRODUCT_REPOSITORY)
    private readonly productRepository: ProductRepositoryPort,
    private readonly storeAuthorizationService: StoreAuthorizationService,
  ) {}

  async execute(
    userId: string,
    command: UpdateProductCommand,
  ): Promise<ProductView> {
    await this.storeAuthorizationService.assertStorePermission(
      userId,
      command.idStore,
      StorePermission.MANAGE_PRODUCTS,
    );

    const existing = await this.productRepository.findById(
      command.idStore,
      command.idProduct,
    );
    if (!existing) {
      throw AppException.from(APP_ERRORS.catalog.productNotFound, undefined);
    }

    const nextName =
      command.name !== undefined ? command.name.trim() : existing.name;
    if (command.name !== undefined && !nextName) {
      throw AppException.from(APP_ERRORS.validation.missingField, {
        field: "name",
      });
    }

    const nextBrand =
      command.brand !== undefined
        ? (command.brand ?? "").trim() || null
        : existing.brand;

    // Re-check uniqueness whenever the name or brand changes. With a brand,
    // only the name/brand pair must be unique; without one, the name alone.
    if (command.name !== undefined || command.brand !== undefined) {
      const clash = await this.productRepository.findByName(
        command.idStore,
        nextName,
        nextBrand,
      );
      if (clash && clash.idProduct !== command.idProduct) {
        throw AppException.from(
          nextBrand
            ? APP_ERRORS.catalog.duplicatedNameForBrand
            : APP_ERRORS.catalog.duplicatedName,
          undefined,
        );
      }
    }

    // SKU is generated by the system at creation and never changes afterwards.
    return this.productRepository.update({
      idProduct: command.idProduct,
      idStore: command.idStore,
      name: command.name?.trim(),
      description:
        command.description !== undefined
          ? (command.description ?? "").trim() || null
          : undefined,
      brand:
        command.brand !== undefined
          ? (command.brand ?? "").trim() || null
          : undefined,
      kind:
        command.kind !== undefined ? assertValidKind(command.kind) : undefined,
      unit:
        command.unit !== undefined ? assertValidUnit(command.unit) : undefined,
      packagingUnit:
        command.packagingUnit !== undefined && command.packagingUnit !== null
          ? assertValidPackagingUnit(command.packagingUnit)
          : undefined,
      packSize:
        command.packSize !== undefined && command.packSize !== null
          ? normalizePackSize(command.packSize)
          : undefined,
      salePrice:
        command.salePrice !== undefined
          ? normalizeSalePrice(command.salePrice)
          : undefined,
      status: command.status,
    });
  }
}
