import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryColumn,
  UpdateDateColumn,
} from "typeorm";
import { AttachmentOwnerType } from "@/modules/attachments/domain/enums/attachment-owner-type.enum";
import { AttachmentStatus } from "@/modules/attachments/domain/enums/attachment-status.enum";

// Only metadata lives in Postgres; the bytes live in object storage under
// `storage_key`. owner_type/owner_id is a polymorphic reference, so there is
// no foreign key: the owner module's policy guarantees the owner exists.
@Entity("tb_attachments")
@Index("IDX_attachments_owner", ["idStore", "ownerType", "ownerId", "position"])
@Index("IDX_attachments_status_created", ["status", "createdAt"])
export class AttachmentEntity {
  // Generated by the application before the upload slot is handed out, so
  // the storage key can embed it.
  @PrimaryColumn("uuid", { name: "idtb_attachments" })
  idAttachment!: string;

  @Column({ name: "idtb_stores", type: "uuid" })
  idStore!: string;

  @Column({
    name: "owner_type",
    type: "enum",
    enum: AttachmentOwnerType,
    enumName: "tb_attachments_owner_type_enum",
  })
  ownerType!: AttachmentOwnerType;

  @Column({ name: "owner_id", type: "uuid" })
  ownerId!: string;

  @Column({
    type: "enum",
    enum: AttachmentStatus,
    enumName: "tb_attachments_status_enum",
    default: AttachmentStatus.PENDING,
  })
  status!: AttachmentStatus;

  @Column({ name: "storage_key", type: "varchar", length: 512 })
  storageKey!: string;

  @Column({
    name: "thumbnail_key",
    type: "varchar",
    length: 512,
    nullable: true,
  })
  thumbnailKey?: string | null;

  @Column({ name: "mime_type", type: "varchar", length: 64 })
  mimeType!: string;

  @Column({ name: "size_bytes", type: "integer" })
  sizeBytes!: number;

  @Column({ type: "integer", nullable: true })
  width?: number | null;

  @Column({ type: "integer", nullable: true })
  height?: number | null;

  @Column({ name: "checksum_sha256", type: "char", length: 64, nullable: true })
  checksumSha256?: string | null;

  @Column({ type: "integer", default: 0 })
  position!: number;

  @Column({ name: "original_name", type: "varchar", length: 160 })
  originalName!: string;

  @Column({ name: "created_by_user_id", type: "uuid" })
  createdByUserId!: string;

  @CreateDateColumn({ name: "created_at", type: "timestamptz" })
  createdAt!: Date;

  @UpdateDateColumn({ name: "updated_at", type: "timestamptz" })
  updatedAt!: Date;
}
